# Generated by Django 5.0 on 2023-12-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
